services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    image: mariadb
    volumes:
      - mdb:/var/lib/mysql
    expose:
      - "3306"
    env_file:
      - .env
    networks:
      - inception_net
    restart: on-failure

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    image: nginx
    volumes:
      - wp:/var/www/html
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - inception_net
    restart: on-failure

  wordpress:
    container_name: wp-php
    build:
      context: requirements/wordpress
    image: wordpress
    volumes:
      - wp:/var/www/html
    expose:
      - "9000"
    env_file:
      - .env
    networks:
      - inception_net
    restart: on-failure

volumes:
  mdb:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/eamsalem/data/mysql
  wp:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/eamsalem/data/wordpress

networks:
  inception_net:
    driver: bridge
