services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - mdb:/var/lib/mysql
    expose:
      - "3306"
    env_file:
      - .env
    networks:
      - inception_net
    restart: on-failure

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wp:/var/www/html
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - inception_net
    restart: on-failure

  wordpress:
    container_name: wp-php
    build: requirements/wordpress
    volumes:
      - wp:/var/www/html
    expose:
      - "9000"
    env_file:
      - .env
    networks:
      - inception_net
    restart: on-failure

volumes:
  mdb:
  wp:

networks:
  inception_net:
    driver: bridge
