services:

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    expose:
      - "3306"
    env_file:
      - .env
    restart: on-failure

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./wp:/var/www/html
    env_file:
      - .env
    restart: on-failure

  wordpress:
    container_name: wp-php
    build: requirements/wordpress
    volumes:
      - ./wp:/var/www/html
    expose:
      - "9000"
    env_file:
      - .env
    restart: on-failure

